icons_format = "{icon}"

[theme]
theme = "solarized-dark"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
icons = "none"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "cpu"

[[block]]
block = "custom"
command = "sensors | rg fan1 | awk '{print $2 \" \" $3}'"
interval = 2

[[block]]
block = "custom"
command = "sensors | rg fan3 | awk '{print $2 \" \" $3}'"
interval = 2

[[block]]
block = "amd_gpu"

[[block]]
block = "temperature"

# [[block]]
# block = "battery"

# [[block]]
# block = "backlight"
# [[block.click]]
# button = "down"
# action = "brightness_up"
# [[block.click]]
# button = "up"
# action = "brightness_down"

[[block]]
block = "custom"
command = "~/bin/ddcbacklight"
format = " $text % "
interval = 30
[[block.click]]
button = "left"
cmd = "~/bin/ddcbacklight 5"
[[block.click]]
button = "right"
cmd = "~/bin/ddcbacklight -5"

# [[block]]
# block = "xrandr"
# format = "   "
# [[block.click]]
# button = "down"
# action = "brightness_up"
# [[block.click]]
# button = "up"
# action = "brightness_down"

[[block]]
block = "disk_space"
path = "/"
# info_type = "available"
# alert_unit = "GB"
# interval = 20
# warning = 20.0
# alert = 10.0
format = " $icon $available.eng(w:2) "

[[block]]
block = "memory"
# format = " $icon $mem_total_used_percents.eng(w:2) "
# format_alt = " $icon_swap $swap_used_percents.eng(w:2) "
format = "$icon $mem_used.eng(prefix:M,w:4)/$mem_total.eng(prefix:M,w:4)($mem_used_percents.eng(w:2))"

[[block]]
block = "sound"
[[block.click]]
button = "down"
action = "volume_up"
[[block.click]]
button = "up"
action = "volume_down"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d %b %R') "
